flybywiresim/discord-bot

src/commands/experimental.ts, src/commands/versions.ts
Now experimental is back in use with cFMS - updated bot commands for .exp and .versions accordingly.
=> Update .versions and .exp for cFMS

src/commands/experimental.ts, src/commands/versions.ts
PR to make slight changes to .exp and .versions currently in staging based on testing commands. 
Footer doesn't support embed - request as per https://github.com/flybywiresim/discord-bot/issues/8#issuecomment-894810549 was to link to versions, moved to own small section to give clarity to that and removed the link part entirely from the footer.
After testing in staging, the split on the "no support" line just makes the command messy and takes up more space than necessary, reformed to pull into the main text. Also removed "version" from following as "Experimental ---- will be updated with the latest changes from both the "autopilot-custom-fpm" branch and development version regularly." reads better when referring to the version by name.
Created a new updated fork removing old one, and …
=> fix: correct experimental commands

src/commands/index.ts, src/commands/installer.ts, src/commands/msfs.ts, src/commands/screenshot.ts, src/commands/versions.ts
- .installer still referenced the A32NX as 'mod', replaced with 'addon'. 
- .versions had outdated content for the Stable and Development sections, mentioned after updating the experimental section, updated these parts based on feedback.
- Added .versions as per https://github.com/flybywiresim/discord-bot/issues/8#issuecomment-894810549 - responds to .screenshot and .cockpit
- Added .msfs as per the same issue - directs to MSFS forums and discord - usable with .msfs and .msfsforum
Testbot results as below:
=> feat: add .screenshot, add .msfs + fixes

src/commands/content.ts, src/commands/index.ts
Adds .content (also takes .contentmanager) to request a screenshot showing the sims content manager, and explain how. 
Test bot results:
=> feat: add .content

src/commands/briefing.ts, src/commands/index.ts
This command provides a link to the A320neo Pilot Briefing on the FBW docs site.
Bot preview:
Discord username: BenW#8484
=> feat: added .briefing

src/commands/boris.ts, src/commands/index.ts
This PR adds a .boris command, calling the GIF [here](https://c.tenor.com/1bIsb5roaSsAAAAd/haggisbandit-sound.gif), a fun one for the server memes similar to .bruheg and .nut.
Built and tested, test results as shown:
=> feat: add .boris gif

src/commands/msfs.ts
Updates the link for .msfs as previous one was a temp link which expired since.  No test bot run as link updated directly through Github. 
=> fix: update .msfs link 

src/commands/calibrate.ts
This PR updates the docs link in .calibrate to the updated link following docs restructure. Command content unchanged and verified. Fully tested.
Test results:
=> fix: update link in .calibrate

src/commands/whois.ts
add the ability to mention user or userID for user information
Test bot results:
Discord username: HyperGame#2143
=> fix: whois command

src/commands/content.ts
This PR updates the image used for .content as per discussions on Discord, and adds a sentence clarifying old/duplicate installs should be deleted.
Test results:
=> fix: update .content command

src/commands/afloor.ts, src/commands/index.ts
Added the .afloor command to link the user to the afloor tool-tips video.
Test results:
Discord username: BenW#0001
=> feat: afloor command

src/commands/calibrate.ts
Only use the Throttle Calibration Guide link in this command as it is not possible to summarize this in a few lines.
Also does not use video as the video does not explain to setup axis in MSFS. 
```
description: makeLines ([
'You need to calibrate your throttles!',
'',
'Please read our [Throttle Calibration Guide](https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flyPad/throttle-calibration/)',
]),
```
Discord: Cdr_Maverick#6475
=> refactor: Changes .calibrate command to only link to guide

README.md
A small change to update the Discord button on the readme to use the vanity URL.
Discord username: `BenW#0001`
=> chore: update to a vanity Discord URL

src/commands/airframe.ts, src/commands/index.ts
Adds a command to share the new simbrief airframe link, responds to .simbrief and .airframe. 
Results:
=> feat: add simbrief airframe command 

src/commands/unban.ts
Fixes the unban permissions, anyone could unban before. You now need to hold the 'ban members' Discord permission to use .unban.
I had the permissions, Nut did not. Working as expected.
BenW#8484
=> fix: unban permissions

src/commands/utf-8.ts
Updates the alias of the UTF8 command from .utf to .utf8 - small change but keeps catching people out. 
Tested, results: 
=> fix: rename command utf8

src/commands/airframe.ts
Replaces the link to the simbrief airframe with the docs page containing both simbrief links rather than the link directly. 
Tested, link directs correctly to the docs page: https://docs.flybywiresim.com/fbw-a32nx/installation/#simbrief-airframe
=> fix: change airframe link to docs

src/commands/msfs.ts
Slightly rewords the .msfs command to state "This is the FlyByWire Discord Server" rather than "Support channel" as the command is often used in other channels and doesn't make much sense.
Test results:
=> fix: reword .msfs to make sense in all channels

src/commands/index.ts, src/commands/willithave.ts
Adds the FBW rule of thumb as suggested by Holland in discord, general answer all to feature questions. 
Responds to .willithave and .thumb (I liked that). 
Results: 
=> feat: add .willithave command

src/commands/afloor.ts
Adds new alpha floor docs to the bot command .afloor alongside video tooltip
Results:
Discord username:  █▀█ █▄█ ▀█▀#2123
=> fix: update .afloor

src/commands/experimental.ts
Updates .experimental to include a link to the docs page [here.](https://docs.flybywiresim.com/fbw-a32nx/support/exp/) 
Test results: 
=> fix: update .experimental with docs link

src/commands/community.ts, src/commands/index.ts
Adds .community (also accepts .com) for support to explain how to find the correct community folder. 
Tested, results updated to latest commit:
=> feat: add .community command to locate com folder

src/commands/a32nx/ctrl_e.ts
As requested by Cdr_Maverick, I have added ctrl-e as an alias for the ctrle command. 
oim#0001
=> feat: added new ctrl e alias

src/commands/index.ts, src/commands/support/logs.ts
As requested by @Valastiri, the .installererror command has been updated to provide instructions on how to send installer error logs. The command has been renamed to .installerlogs and .logs . The #deleted-channel in the screenshot is due to the channel id being the actual FBW support channel. 
oim#0001
=> feat: updated error command to provide error log instructions

src/commands/index.ts, src/commands/utils/avatar.ts
Commonly used dyno feature. Sends an embed of the requested user's profile picture. Commands are:
.avatar <user>
.av <user>
If a user is not specified, the message author's profile picture will be displayed. 
oim#0001
=> feat: added avatar command

src/commands/utils/help.ts
feat: decide between DM or docs when using help command
Presents an emote selector when using the `.help` command
`.help`
`Select 2`
nistei#1362
=> feat: decide between DM or docs when using help command

src/commands/a32nx/freetext.ts, src/commands/index.ts
Provides a link to instructions on how to use the freetext feature in the A32NX. Aliases are .freetext and .ft . 
oim#0001
=> feat: added freetext command

src/commands/a32nx/printer.ts
https://github.com/flybywiresim/a32nx/pull/6088
This pull request may fix the printer CTD. If the QA team has found that it does fix it, this PR should be merged. It removes the disclaimer that the printer may cause CTDs. 
oim#0001
=> fix: remove CTD disclaimer in .printer

src/commands/a32nx/experimental.ts, src/commands/a32nx/versions.ts, src/commands/funnies/cowsay.ts, src/commands/index.ts, src/commands/support/tug.ts
This PR applies minor typo corrections to .exp and .versions that slipped through the initial update and copychecks. 
Also applies line breaks to .tug and moves .cowsay into the funnies command category.
Test results: 
=> refactor: minor improvements to .exp, .versions, .tug and move .cowsay

src/commands/moderation/faq.ts
Changes the FAQ section to advise users to message mod team rather than just two users for pilot verification
Will show moderation team role when merged, checked with a role ID from test server and works all fine!
=> fix: add mod team role ID to .faq

src/commands/general/goldenrules.ts, src/commands/index.ts
As requested by Cdr_Maverick, I have added the golden rules command. It provides an image of the golden rules an Airbus pilot should follow. Aliases are .golden, .goldenrules and .gr
oim#0001
=> feat: added goldenrules command

src/commands/funnies/fridge.ts
changed the .fridge image to another cleaner version of that image.
oim#0001
=> fix: fixed fridge image

src/commands/moderation/faq.ts, src/commands/moderation/welcome.ts
Replaces emote ID's in .welcome for use in prod bot with new emojis.
Also corrects a 404'd link to docs FAQ as raised on discord. Redirects to https://docs.flybywiresim.com/fbw-a32nx/faq/
Tested, link works on .faq update, as for .welcome won't show properly until merged into prod as the emotes have different ID's. 
=> fix: .welcome emotes and .faq docs link

src/commands/a32nx/assistance.ts, src/commands/index.ts
As requested by mav, the assistance command explains to the user why all assistance options should be disabled. Aliases are:
.assistance
.assi
.as
oim#0001
=> feat: added assistance command

src/commands/a32nx/mcdu.ts, src/commands/index.ts
add remote .mcdu command to link to a32nx remote mcdu feature guide
aliases: .mcdu, .remotemcdu, .remote
=> add remote mcdu command

src/commands/a32nx/takeoffPerf.ts, src/commands/index.ts
Adds a .takeoff (.calculator, .perf) command which explains why there is no takeoff performance calculator available.
=> feat: Add .takeoff command

src/handlers/messagedelete.ts
Previously the deleted messages sent to #userlogs wouldn't include images. This fixes that. Messages deleted that included that image should now include a link to that image in userlogs. 
oim#0001
=> fix: messagedelete handler now includes deleted images

src/commands/index.ts, src/commands/support/wasm.ts
Requested by boris for support purposes. Explains the long loading times that users may encounter after a first install/update. Aliases are .wasm and .load
oim#0001
=> feat: added wasm command

src/commands/a32nx/CPDLC.ts, src/commands/index.ts
This PR adds .CPDLC to support the merging of https://github.com/flybywiresim/a32nx/pull/6451 as discussed over discord with Mav and the the PR author Sven.  The command links to https://docs.flybywiresim.com/fbw-a32nx/feature-guides/hoppie/ pending the docs PR merge.
Responds to .CPDLC, .PDC, .Hoppie and .ACARS,
Not to be merged until #6451 and related docs PR are merged. PR raised now for approval so merge can be done whenever the others go ahead.
=> Feat: add .CPDLC command

src/commands/a32nx/simbriefimport.ts, src/commands/index.ts
feat: SimBrief integration command
The command shows users how to use SimBrief integration, with an image showing how it will look when everything is done correctly, and to the docs referring to how to set it up.  Commands are: import, integration,  integ
zx#0671
=> feat: SimBrief integration command

src/handlers/messagedelete.ts, src/handlers/messageupdate.ts
This PR fixes a crash when an `old message` is deleted or updated. The message is not cached by the bot, therefore it can't receive message content, author etc. This fix will ignore the message if the content of the message = null. The message content is null due to `old message` not cached. 
`old message` refers to a message that has been sent before the bot has been brought online.
N/A
Tested locally and in a docker container. Both working.
BenW#8484
=> fix: message delete/update crash

src/commands/a32nx/experimental.ts, src/commands/a32nx/versions.ts
Updates to `experimental.ts` and `versions.ts` to reflect the current status of the experimental branch.
Both commands I've imported `makeLines` to break up the copy and make it a little more readable. See indicated line breaks in screenshot below.
Commands are in support of docs PR below. Please notify docs team when moving commands to production.
- https://github.com/flybywiresim/docs/pull/468
Valastiri#8902
=> refactor: update commands that reference status of experimental branch

src/commands/index.ts, src/commands/moderation/timeout.ts, src/commands/moderation/untimeout.ts
Implements the discord timeouts feature in a .timeout command. 
Tasks: 
Some limitations:
* There is no event for timeouts being added or removed. Therefore, it's not feasible to create an event handler for timeouts (to account for right-click timeouts). This can come at a later time if an event becomes available.
* Removing a timeout is done by setting 0 for timeout duration. There is no official 'remove timeout' method for GuildMember. This is how discord itself handles removing timeouts.
* Maximum timeout length is 3 weeks. Discord.js / API restriction.
Timeout command + response: 
Message sent to user when timed out:
Message sent in modlogs when timeout set by the bot
Removing timeout via setting 0-length timeout (msg. 1) or using .untimeout (msg. 2): 
Message sent to user when …
=> feat: .timeout

src/commands/a32nx/tcas.ts, src/commands/index.ts
**Note** - Please wait for docs PR:
- https://github.com/flybywiresim/docs/pull/472
Provides a snapshot of A32NX AP/FD TCAS and links to the expanded documentation on the feature.
Valastiri#8902
=> feat: tcas command

src/commands/utils/metar.ts, src/commands/utils/station.ts
Current implementation of the METAR & station commands do not properly handle erroneous responses from the AVWX API, and cause the bot to restart if any are received (see below for behavior). Normal response codes include 200 (response OK) and 400 (client error, in this case invalid ICAO/IATA code). This implements a check on the response status code, avoiding a crash caused by attempting to access body fields that do not exist in erroneous responses.
pererry#8489
=> fix: metar/station command error handling

src/commands/support/clean-install.ts
The original link had the mkdocs-material `/?h=clean+install` search query in the hyperlink causing highlighting across the page which may be distracting for readers since there's a dedicated anchor link available.
For posterity - link works in testing.
Valastiri#8902
=> refactor(clean): remove search query string from hyperlink

src/commands/general/synaptic.ts
Updated synaptic.ts with the new vanity url. Aliases are still .synaptic and .syn
zx#0671
=> Refactor: Updated synaptic discord invite link 

src/commands/a32nx/weather.ts
fix: Include stable in wx command
Update WX command to include stable in the list of versions with no terrain or weather raddar
fix: Include stable in wx command
=> fix: Include stable in wx command

.github/CHANGELOG.md, .github/command-docs.md, src/commands/general/salty.ts
Adds .ninjo as an alias to the .salty command. Ninjo is the admin of Salty Simulations.
oim#0001
=> refactor: add .ninjo as an alias to salty command

src/commands/utils/avatar.ts
Before this PR the avatar command did not accept user IDs. Instead it would just show the author's avatar. 
oim#0001
=> fix: avatar command now accepts user ids

src/commands/moderation/untimeout.ts
.removetimeout is an alias for the untimeout command but would throw an error if used. This pr fixes that.
oim#0001
=> fix: allow the use of the .removetimeout alias for .untimeout

.github/CHANGELOG.md, src/commands/a32nx/experimental.ts
Removes flypad thread link from the .exp command.
=> fix: remove flypad thread from exp 

.github/CHANGELOG.md, src/commands/index.ts, src/commands/support/simbridge.ts
Provides a short description of simbridge and utilizes copy to aid in support if users have not kept the feature updated within the installer.
Additionally provides a link to documentation. Please do not merge until the following is ready on docs:
- https://github.com/flybywiresim/docs/pull/601
---
There was a discussion between BenW and myself to put this in general. Can move if required just suddenly thought it might be more useful as a support command as discussed with Holland.
Valastiri#8902
=> feat: simbridge support command

.github/CHANGELOG.md, .github/workflows/verify-changelog.yml
A simpler test and does not use PR commenting. Previous PR:
- #267 
Utilizes a label that would need to be created: `skip changelog` to bypass the check if a changelog is not required.
Failed Changelog Test (no changelog in PR)
https://cdn.discordapp.com/attachments/825674445342638120/1006657569286258699/unknown.png)
Action types re-runs check when labeled or unlabelled.
Valastiri#8902
=> ci: verify changelog in PR

.github/CHANGELOG.md, .github/command-docs.md, src/commands/general/doc.ts, src/commands/general/docsearch.ts, src/commands/index.ts
feat: doc command to search documentation
This command has the following functionality:
* Listen to `.doc`, `.docsearch` and `.documentation`
* If no argument is given, it provides a link to the documentation website
* If an argument is given (one or more words), it provides a link to the documentation search functionality
* It checks for profanity
* It checks for URLs to minimize the risk of abusing the bot for pushing your own URL into a bot output
* It URI encodes the search to prevent injection of unwanted characters in the URL itself
Positive cases
Negative cases
straks#7240
=> feat: docsearch command to search documentation

src/commands/moderation/temporaryCommandEdit.ts
Fixing the permission messaging and only requiring the specific roles (ADMIN or MODERATOR)
<Needs final test on test server>
straks#7240
=> fix: temporaryCommandEdit - Improve permission validation and messaging

.github/CHANGELOG.md, .github/command-docs.md, src/commands/a32nx/flyPadOS.ts, src/commands/index.ts
Provides a command that will return links to the flyPadOS3 documentation
per chapter, and includes a link for the older flyPadOS2 documentation.
straks#7240
=> feat: flypados command for flyPadOS3 documentation

.github/CHANGELOG.md, .github/command-docs.md, src/commands/a32nx/verticalGuidance.ts, src/commands/a32nx/verticalGuidanceSymbols.ts, src/commands/a32nx/verticalSpeedPriority.ts, src/commands/index.ts
Provides 3 new commands:
* verticalguidance, vnavdoc, vnav: Provides links to the Vertical
Guidance documentation.
* verticalguidancesymbols, vnavsymbols, vnavnd: Provides a link to the
Vertical Guidance Navigation Display Symbols documentation.
* verticalspeedpriority, vspriority, fpapriority, vspeed: Explains the
priority of V/S and FPA over speed guidance and provides a link for
more details.
straks#7240
=> feat: verticalguidance, verticalguidancesymbols and verticalspeedpriority commands

.github/CHANGELOG.md, .github/command-docs.md, src/commands/a32nx/mcdu.ts, src/commands/a32nx/remoteMcdu.ts, src/commands/index.ts
Advanced MCDU documentation command. Does require removing the `.mcdu` alias from the `.remotemcdu` command, als refactored the file for that to be in line.
Work in progress: pending flybywiresim/docs#191
straks#7240
=> feat: mcdu command for the detailed MCDU documentation

.github/CHANGELOG.md, src/commands/moderation/ban.ts
Small fix to prevent a crash when banning a moderator. There was an error in the handling for when the bot had incorrect permissions. (Bot sits below Admin and Moderator roles, hence throwing an error when trying to ban - this is normal)
`!targetUser.moderatable` is now also used to prevent trying to ban a moderator in the first place.
BenW#8484
=> fix: crash when banning a moderator

.github/CHANGELOG.md, src/commands/general/temporaryCommand.ts, src/commands/moderation/temporaryCommandEdit.ts, src/lib/schemas/temporaryCommandSchema.ts
This adds the following features to the temporary commands:
* Support for an image
* Track when the command was last used for easier decision on when
to delete it
* Mod log shows who took an action specifically, not just which mod
created the temporary command
straks #7240
=> feat: Add image and last used functionality to temporary commands

.github/CHANGELOG.md, .github/command-docs.md, src/commands/a32nx/atc.ts
After discussions with some developers, it was suggested to enhance the ATC command and documentation to clarify that there's not only the sync method, but also just using the world planner itself, if users would like to. 
straks#7240
=> refactor: update the ATC command for more clarity and more options

.github/CHANGELOG.md, src/commands/moderation/temporaryCommandEdit.ts
A previous refactor of arg parsing broke the parsing of the help sub command, this fixes that. 
**Before**
**After**
straks#7240
HowNowBrownCrow#2591 for reporting and providing first fix proposal in Heavy-Division/heavy-division-bot#55 ( @nakajimayoshi )
=> fix: bugfix where help subcommand was not working for tcedit

.github/CHANGELOG.md, src/commands/utils/help.ts
The commands in the DM for help are not alphabetically sorted, this is confusing. This PR fixes that.
NOTE: In the commands/index.ts, it makes sure that the list of names is _always_ an array/list:
https://github.com/flybywiresim/discord-bot/blob/ea7cbf3af47b5089b5b719b13ec120b11fe61bc3/src/commands/index.ts#L316
straks#7240
=> refactor: sort commands in help alphabetically

.github/CHANGELOG.md, .github/command-docs.md, package-lock.json, src/commands/index.ts, src/commands/moderation/sticky.ts, src/handlers/forumPostCreate.ts, src/lib/schemas/stickyMessageSchema.ts, src/lib/stickyMessageEmbed.ts
With the introduction of Forum Channels, there is a need for an automated message posted by the bot every time someone creates a new post. This is especially important for Support channels. 
This PR introduces the possibility to configure a message for a Forum Channel that will get posted every time a Forum Post is created. 
[_See the Video in Test Evidence for a breakdown_](#test-results)
With the introduction of Forum Channels, there is a need for an automated message posted by the bot every time someone creates a new post. This is especially important for Support channels. 
Summary of requirements:
- Manage a (single) message per channel that gets posted in every new Forum Post created in that channel. 
- The message can contain multiple lines
- The message can contain basic markdown …
=> feat: stickies for forum posts which get posted on forum post create 

.github/CHANGELOG.md, .github/command-docs.md, src/commands/aircraft/atc.ts
Simple alias for the ATC command now that it includes more details on flight planning. 
straks#7240
=> refactor: add flightplanning alias to atc command

.github/CHANGELOG.md, src/handlers/forumPostCreate.ts
The Forum Post create Handler to post a sticky message into each Forum Post (Thread) could encounter a race condition where it tried to post the sticky message before Discord was finished setting up the thread properly. 
This caused an exception and the bot to crash. 
The internal exception is: ```Exception has occurred: DiscordAPIError[40058]: Cannot message this thread until after the post author has sent an initial message```
This is more likely on messages that require more processing by the Discord API, most easy way to reproduce it to post a (very) large image as part of the new Forum Post.
Note: Even with a large image, it doesn't always trigger the race condition. Testing revealed about 80% chance with an image of 4.5MB in size. The smaller the size, the less likely it is to …
=> fix: forum post handler was too fast for Discord API and tried to post before the thread really existed

.github/CHANGELOG.md, .github/command-docs.md, src/commands/index.ts, src/commands/moderation/cacheUpdate.ts
In certain situations it could be useful to force a cache update of the bot. (look at issue #395 for instance). This command allows the most typical caches to be updated fully.
straks#7240
=> feat: cacheupdate command to update the bots cache on different server aspects

.github/CHANGELOG.md, src/commands/utils/roleinfo.ts
The original PR with fetching the role and updating the cache is not fixing the problem. It just updates the role cache, not the member cache... 
Likely root cause:
* The command gets the size of the collection of members on a Role
* The collection of members on a role is based on the members known in the cache that have that role
* Members are only added to the cache if the bot has interacted with them and handled a command from them (or perhaps has seen a message from them) since its last start.
So for all members that haven't been actively online, the member information (including roles) has not been added to the cache and so they are not part of the cached collection.
roleinfo is giving the wrong counts 
VS
Initial thoughts are that this is a caching issue as the cache isn't refreshed …
=> fix: roleinfo showing wrong count because of caching

.github/CHANGELOG.md, .github/command-docs.md, src/commands/general/navigraph.ts, src/commands/index.ts, src/commands/support/navigraphNavdata.ts
Simple link to the Navigraph Discord server... Had to rename the navigraph data command though. 
Reference: https://github.com/flybywiresim/discord-bot/projects/1#card-86854395
straks#7240
=> feat: navigraph discord link

.github/CHANGELOG.md, .github/ISSUE_TEMPLATE/bug_report_beta.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request_beta.yaml, .github/command-docs.md, src/commands/index.ts, src/commands/support/botIssue.ts
Adds two issue types that can be created on the repo for tracking bugs and feature requests.
Also provides the command to link to creating a new issue/feature request for the bot. 
straks#7240
=> feat: Adding issue templates and accompanying command

.github/CHANGELOG.md, .github/command-docs.md, package-lock.json, package.json, src/commands/index.ts, src/commands/moderation/slowmode.ts, src/index.ts, src/lib/scheduler.ts, src/lib/scherdulerJobs/autoDisableSlowMode.ts
This introduces a few new items:
* A Scheduler based on Agenda (https://github.com/agenda/agenda), which will be used in the future for more than just the slowmode feature (which is why it's a full package with complex functionality, including triggering on bot restart, so schedule is persistent)
* Slow mode command that can:
* Configure slow mode for a channel, both locally and remotely
* Configure an auto disable timeout, the bot will automatically disable slow mode again
The agenda package uses two variables that come into play with persistency: 
* processEvery - Determines how often the scheduler looks at the database for waiting/open jobs and takes a lock on them. Set here to 30 seconds.
* defaultLockLifetime - How long a lock lasts. Set here to 30 seconds.
When agenda checks every …
=> feat: slowmode with timeout and introducing proper scheduler

.github/CHANGELOG.md, src/commands/aircraft/airframe.ts, src/commands/aircraft/atc.ts, src/commands/aircraft/experimental.ts, src/commands/aircraft/flyPadOS.ts, src/commands/support/reportedissues.ts
Updates copy of various commands and fixes broken links:
- exp
- update the copy to be more general with VNAV as the main mention
- update URL to `/exp` in case the page is ever moved or restructured at a later time (internal redirect on docs site)
- airframe
- update the docs URL to its new location to prevent more clicks
- reported-issues
- Since this is our project might as well have it correct + up2date and using the newer `/reported-issues` internal redirect. Same reasoning as the exp command in the case page is ever moved or restructured at a later time.
- atc
- Minor capitalization fix
- flypadOS
- Remove links to flyPadOS 2. Documentation no longer exists and the version is deprecated
Links were tested and all working
Valastiri#8902
=> refactor: update and fix various commands

.github/CHANGELOG.md, src/commands/moderation/timeout.ts
Adds the date to the warn doc for timeouts - this was missed when initially adding functionality.
The date format has also been changed to match other mod log entries.
Before - These were all created apart from each other - see the time is the same as when command is called:
After - See the last two, although close, they are different and are not the same as the command call time:
BenW#8484
=> fix: adds date to warn doc for timeouts

.github/CHANGELOG.md, src/handlers/birthdays.ts
* moved fetching of birthdays after DB conn check to fix bug. Before the
fetch of birthdays could happen without DB conn present which would
return an empty list. This could happen if the db connection had timed
out. Which meant the BDs were just never fetched until there happened
to be an already active DB conn.
* Cleaned up comments, logging and collapsed new lines for readability
improvements
* Included logging for every execution, to better keep track of handler
execution
* Changed execution to every 30 minutes instead of once an hour to get
the birthday message closer to the preferred time
Tested by setting runtime to 1 minute and executing it with multiple birthdays. Bug testing is more difficult as it needs DB timeout to happen, but logic is solid.
straks#7240
=> fix: birthday handler random delays bug

.github/CHANGELOG.md, src/commands/support/utf-8.ts
Adds an 's' to various system(s).
This is in addition to Beheh's PR #444 to fix the link as well.
Valastiri#8902
=> fix: grammar and hyperlink in embed for utf-8.ts

.github/CHANGELOG.md, .github/workflows/verify-changelog.yml
Prevents the changelog verifier workflow from running on forks and when the pr is still a draft. (copied from the docs repo)
Changelog still has to be provided before merging, except with the no changelog tag.
Slein#8982
=> feat: prevent changelog verification on fork

.github/CHANGELOG.md, src/commands/moderation/warn/deleteWarn.ts
Fixes the ping in the mod log for warning deletes.
Top: Before
Bottom: Fix
BenW#8484
=> fix: ping in delete warning mod log

.github/CHANGELOG.md, src/commands/support/build.ts
Removed an exclamation mark from .build command, as that isn't a warning, and as per contributing guidelines, exclamation marks shouldn't be used, if it isn't a warning.
=> fix: remove exclamation mark in .build

.github/CHANGELOG.md, src/constants.ts, src/lib/command.ts
Before, if verbose errors were enabled and the constants.ts did not have the correct IDs, the bot would crash. This adds a protection and fallback to the default error message.
It also autodeletes the command itself, not just the error message.
And to clarify to the user, it mentions in the error message that it will be autodeleted after the configured time (if configured, which it should be)
straks
=> feat: Adding protection if parsing channels or roles fail and autodelete command

.github/CHANGELOG.md, src/commands/utils/simbriefdata.ts
- allow simbriefId being in <>
- show an error message if command incl <pilotId> as simbriefId is just copied
- add short Text if the airframe is the one provided by FBW
slein15
=> feat: Optimize simbriefdata for input error

.github/CHANGELOG.md, src/commands/moderation/timeout.ts
Removes the autodelete of timeout command and response
Fixes a bug where timing out with 0 would not actually remove the timeout, but throw an error instead.
straks
=> fix: Removing autodelete of timeout command and response, fixing bug with untimeout

.github/CHANGELOG.md, src/handlers/messagedelete.ts
Introduces the following to the user delete log handler:
* Optimize embeddings
* Adds data for when embeds get deleted (text and urls for images for instance)
* Adds details if attachments are used
* Adds reference to a message if the deleted message is a reply to another message (ghost ping prevention among one of the reasons)
straks
=> feat: Adding support for embeds and referenced messages in delete log

.github/CHANGELOG.md, src/commands/aircraft/versions.ts
=> fix: update A32NX download links

.github/CHANGELOG.md, src/commands/support/screenshot.ts
This is a _very_ minor improvement to the `.screenshot` command (better known as `.ss`). It adds an explanation for why a screenshot is necessary.
---
While at it, I also changed some other minor things:
* Direct link to the [MS Snipping Tool docs](https://support.microsoft.com/en-us/windows/open-snipping-tool-and-take-a-screenshot-a35ac9ff-4a58-24c9-3253-f12bac9f9d44) (taken from [FBW docs - How to Take a Good Screenshot](https://docs.flybywiresim.com/fbw-a32nx/support/#how-to-take-a-good-screenshot)).
* Visually emphasize the elements needed to be visible in the screenshot.
* Improve text layout for better readability.
* Update embed title to reflect change in meaning.
At the moment, just sending the command in response to a support request may come across a bit condescending as the …
=> refactor: improve screenshot cmd

.github/CHANGELOG.md, src/commands/aircraft/flex-temp.ts, src/commands/aircraft/takeoffPerf.ts
=> fix: Update takeoff calculator command to highlight new ongoing development
