package-lock.json, package.json, src/index.ts, src/lib/logger.ts
Switch to [ECS-Logging](https://www.elastic.co/guide/en/ecs-logging/overview/current/intro.html) in production mode and use APM to generate transactions which can be found in the logs.
ECS logging format can be parsed by Filebeat and indexed into Elasticsearch for log aggregation.
```{"@timestamp":"2021-07-08T21:44:24.383Z","log.level":"info","message":"Running command 'when'","ecs":{"version":"1.6.0"},"event":{"dataset":"discord-bot.log"},"trace":{"id":"75bb5df8c3d79f4dc4090e2bf23c2493"},"transaction":{"id":"2d6c9675a9f477a1"},"service":{"name":"discord-bot"}}
{"@timestamp":"2021-07-08T21:44:27.663Z","log.level":"info","message":"Running command '.'","ecs":{"version":"1.6.0"},"event":{"dataset":"discord-bot.log"},"trace":{"id":"b315923fe37a88205ade6afd55a3fd24"},"transaction":{"id":"4571c …
```
=> feat: ECS-Logging and transactions

src/commands/index.ts, src/commands/nut.ts
A fun command (like bruheg) making light of the amount of times nut has said 'Please read, read the sticky'.
This can be made moderator only etc. if it isn't wanted publically.
=> feat: add .nut

src/commands/controls.ts, src/commands/msfs.ts
- Reformats and shortens .controls for readability and refers to docs for the full guide and details as per feedback on Discord.
=> Fix: cockpit interaction reformat

src/commands/help.ts, src/commands/index.ts, src/handlers/messagedelete.ts, src/index.ts
- Generates interactive embeds with a maximum length of 1024 characters per field.
- Fixes insufficient error handling of the message delete handler.
- Adds error logging
=> feat: interactive help command

src/commands/beginner-guide.ts, src/commands/index.ts
This command provides a link to the Beginner's Guide on the FBW docs site.
Bot preview:
Discord username: BenW#8484
=> feat: added .beginnerguide

src/commands/index.ts, src/commands/xbox.ts
Adds xbox.ts and updates index.ts to add a short response and link to full NOTAM regarding xbox + marketplace. 
=> feat: add .xbox command for marketplace+xbox notam

src/commands/faq.ts, src/commands/index.ts
Added the FAQ embed, the intent is to be able to update this when needed through a command.
BenW#8484
=> feat: add faq embed

src/commands/index.ts, src/commands/roadmap.ts
Adds .roadmap to call the roadmap image [here.](https://cdn.discordapp.com/attachments/740722295009706034/893674991667798026/ROADMAP.png)
Tested, result: 
=> feat: add roadmap command

src/commands/adirs.ts
Update the image in .ADIRS
BenW#8484
=> fix: update .adirs image

src/commands/clean-install.ts, src/commands/index.ts
Adds the clean install command (.clean, .clean install, .cleaninstall, .order66)
BenW#8484
=> feat: clean install command

.github/CONTRIBUTING.md, src/commands/index.ts
Minor change to the order of index.ts so new commands can be added directly to the bottom of the import section. Done to refine the process for easier commits and simpler process for new contributors to the repo.
Also updates contributing.md to reflect the change.
Tested: No new commands tested, ran through the list via NUTBOT to verify still working as expected. 
=> chore: organise index.ts and update CONTRIBUTING.md for simpler contributing

src/commands/index.ts, src/commands/support/cursor.ts
This command gives steps on how to un-focus the cursor from the EFB.
(.cursor, .efbfocus, .unfocus)
BenW#8484
=> feat: added .cursor

src/commands/funnies/ptu.ts, src/commands/index.ts
Migrated the ptu command from Dyno bot. Provides a ptu related image. Command is .ptu
oim#0001
=> feat: added ptu command

README.md
Updated the readme to include the discord bot channel and added a few periods. 
oim#0001
=> docs: updated .readme to include the discord bot channel

src/commands/funnies/coffee.ts, src/commands/funnies/default.ts, src/commands/funnies/guard.ts, src/commands/funnies/juan.ts, src/commands/funnies/merge.ts, src/commands/funnies/otter.ts, src/commands/funnies/p3d.ts, src/commands/funnies/poggers.ts, src/commands/funnies/pov.ts, src/commands/funnies/shame.ts, src/commands/funnies/xp.ts, src/commands/index.ts
This PR Ports over our custom imaged based Dyno memes.
Guard
Poggers
Merge
Default
Juan
P3D
Xp
Pov
Coffee
Otter
Too many to post on PR. All tested and working well.
BenW#8484
=> feat: port over image based dyno memes

src/commands/funnies/whened.ts, src/commands/index.ts
Adds a "you just got whened" meme requested by a few users using the nut meme format. 
- Called by .whened
Tested: 
=> feat: add .whened meme

src/commands/utils/help.ts
Updates the link in .help to a shortened version.
BenW#8484
=> chore: .help link update

.github/workflows/production.yaml, .github/workflows/staging.yaml, charts/discord-bot/templates/secret.yaml, charts/discord-bot/values.yaml
Sets the correct METAR token when deploying to Kubernetes.
N/A
BenW#8484
=> ci: Set STATION token in Kubernetes pods and workflows

.github/workflows/production.yaml, .github/workflows/staging.yaml
Fix STATION_TOKEN in workflows
N/A
BenW#8484
=> fix (ci): STATION_TOKEN

src/commands/funnies/addon.ts, src/commands/index.ts
Adds a 'not a mod, its an addon meme' for further warping next holiday!
Test results: 
=> feat: Addon meme

src/constants.ts
* Change FBW cyan color from #00C2CB to #00E0FE to fit with new branding
New then old
@someperson#4953
=> fix: change fbw cyan color

src/commands/index.ts, src/commands/support/discontinuity.ts
Provides a link to docs regarding discontinuities
BenW#8484
=> feat: .discontinuity

src/commands/index.ts, src/commands/support/fdr.ts
Provides information on how to send FDR files for further investigation.
BenW#8484
=> feat: flight data recorder

src/commands/a32nx/cfms.ts, src/commands/index.ts
Informs users and provides a link to docs regarding cFMS merge
BenW#8484
=> feat: cFMS information

src/commands/index.ts, src/commands/support/build.ts
Command gives instructions on how to provide build info
BenW#8484
=> feat: .buildinfo

src/commands/index.ts, src/commands/support/navdata.ts
Gives instructions on how to remove and re-install Navigraph navdata
BenW#8484
=> feat: .navdata 

src/commands/a32nx/weather.ts
updated the weather command to include the development version of the a32nx. 
oim#0001
=> fix: update weather command to include development version of a32nx

src/commands/utils/help.ts
The .help command now pings the correct user when selecting option 1 (DM) on the embed. Before it used to ping/reply to itself.
BenW#8484
=> fix: .help now pings correct user

src/commands/general/directx12.ts, src/commands/index.ts, src/commands/support/directx12.ts
Since the release of Sim Update 7 and the addition of DirectX 12 support, the server has received many questions regarding it.
This PR adds a simple explanation command of the current state of MSFS, FBW and DX12 via ".dx12".
=> feat: Add DirectX 12 command

src/commands/funnies/whended.ts
Adds .whended ! Command pastes this video: https://cdn.discordapp.com/attachments/740722295009706034/912043650601586769/dot_when.mov
Erick [Z-6]#6484
=> feat: add whended funny!

src/commands/funnies/whended.ts, src/commands/funnies/wheneded.ts, src/commands/index.ts
Changed the name of .whended to .wheneded and adds it to index.ts
Erick [Z-6]#6484
=> refactor: add wheneded to index

src/commands/funnies/crak.ts, src/commands/index.ts
=> feat: add crak funny

src/commands/index.ts, src/commands/moderation/rules.ts
.rules has been added. This will enable us to re-send the embeds in the current #rules Discord channel to maintain the new branding. (BAN_MEMBERS permission must be held to send the command - moderator and admins)
BenW#8484
=> feat: add .rules

src/commands/a32nx/weightBalance.ts, src/commands/index.ts
Explains the features of the new fuel and weight system on the A32NX and provides a link to a guide on how to use it.
oim#0001
=> feat: added weight and balance command

src/commands/a32nx/fixinfo.ts, src/commands/index.ts
adds .fixinfo, which provides information about the fix info feature.
=> feat: fix info command

src/commands/a32nx/fixinfo.ts
Updates to correct link
N/A
BenW#8484
=> fix: Update link in .fixinfo

src/commands/a32nx/efb.ts
Updated EFB gif to match the newer GIF and shows the user where to click.
Cleon#5802
=> feat: update EFB gif

README.md
Updates the readme.md to include other maintainers of the bot repository.
N/A
oim#0001
=> docs: update readme.md to include other maintainers

src/commands/a32nx/afloor.ts, src/commands/a32nx/fixinfo.ts
Updates links to docs for https://github.com/flybywiresim/docs/pull/317 on .afloor and .fixinfo
=> fix: update .afloor and .fixinfo docs links

src/commands/general/roadmap.ts
Updates roadmap image to fit with new branding.
BenW#8484
=> fix: update .roadmap image

src/commands/a32nx/checklist.ts, src/commands/a32nx/sop.ts, src/commands/index.ts
Command provides a link to download the SOP as a PDF
(Small update to .checklist in this PR, nothing notable)
BenW#8484
=> feat: add .sop

src/commands/funnies/fridge.ts, src/commands/index.ts
Fridge. Requested by nuts. 
oim#0001
=> feat: added fridge command

src/commands/a32nx/tiller.ts, src/commands/index.ts
Provides a link to the separated tiller axis guide. Frequently asked in support. 
oim#0001
=> feat: added tiller command

README.md
Readme header has been updated to conform with new branding.
BenW#8484
=> style: readme header

src/commands/utils/ping.ts
Changes .ping to be moderator only using required permissions: ban members.
=> fix: .ping perms to be moderator only

src/commands/a32nx/checklist.ts
Fixed the .checklist embed image to match the downloaded version.
oim#0001
=> fix: update .checklist image to match download

src/commands/index.ts, src/commands/support/ctd.ts
As requested by Mav, I have added the .ctd command. It provides a link to the docs page on tips on how to deal with CTDs.
oim#0001
=> feat: added .ctd

src/commands/funnies/poggers.ts
Requested by Kiwi. Added .pog alias to the .poggers command
oim#0001
=> feat: added new .poggers alias

src/commands/a32nx/experimental.ts, src/commands/a32nx/versions.ts
Updates .exp and .versions for latest experimental changes when exp goes live again in the installer. 
PENDING EXPERIMENTAL RELEASE PRIOR TO MERGE
=> update: .exp and .versions for latest experimental changes

src/commands/index.ts, src/commands/support/hud.ts
Adds HUD command to the support section
Cleon#5802
=> feat: add HUD command

src/commands/funnies/fms.ts, src/commands/index.ts
.fms command meme
requested by holland
=> feat: .fms command meme

src/commands/index.ts, src/commands/support/manual.ts, src/commands/support/manualleg.ts
adds manual command to support category
Cleon#5802
=> feat: add manual command

src/commands/support/discontinuity.ts
Changed link to correct documentation for .disco command
Not tested
Cdr_Maverick#6475
=> fix: Changed discontinuity link

src/commands/funnies/oim.ts, src/commands/index.ts
=> feat: oim meme

src/index.ts
This helps us prevent against scams (mainly nitro scams) as many scams have the @ everyone ping due to mass copy and paste. When our bot sees a message with this ping, it will delete the message and give the member our muted role. It will then send the moderation team a message in a logs channel where they can see the user and the message they sent, appropriate action can be taken.
A dm will also be sent to the user explaining what has happened, this is especially helpful if the bot picks up a false positive (someone joking with the @ everyone ping). The user will know why it was deleted and why they are muted and can wait for the moderation team to rectify the false positive.
The core team have been excluded from this as @ everyone is sometimes used by them. A warning in the logs channel …
=> feat: scam prevention

src/commands/a32nx/simbriefimport.ts
* SimBrief -> simBrief
* MCDU -> FMS
* More appropriate punctuation
=> fix: simBrief command cleanup

tsconfig.json
Fixes the 'cannot find' some node_modules error.
BenW#8484
=> fix: fixes node_modules error

src/index.ts, tsconfig.json
This fixes a crash when deploying to docker.
Tested in a local docker container and works as expected.
BenW#8484
=> fix: fixes crash when deploying to docker

src/commands/moderation/whois.ts
Fixes the offline status giving `null` in `.whois`. (New way of doing it in discord.js v13) 
BenW#8484
=> fix: offline status for whois

src/index.ts
Fixes a crash when user DM's bot. This will need looking at as you can no longer DM the bot with a command. (.help still does work)
I have disabled DM communication with the bot for the time being.
BenW#8484
=> fix: DM crash

src/commands/moderation/timeout.ts, src/commands/moderation/untimeout.ts
catch a few errors that could crash the bot in the timeout and untimeout commands
=> fix: prevent various crashes in timeout and untimeout

src/commands/a32nx/audio.ts
Fix command category mistake in `audio.ts`. 
Valastiri#8902
=> refactor: audio.ts command category

src/commands/a32nx/custom-waypoint.ts, src/commands/a32nx/flex-temp.ts, src/commands/a32nx/preflight.ts, src/commands/a32nx/stored-waypoint.ts, src/commands/index.ts, src/commands/moderation/rules.ts
Adds suggested commands from a while ago.
`.flex` `.waypoint` `.preflight`
Updates .rules to state server language
BenW#8484
=> feat: add suggested commands

src/commands/a32nx/experimental.ts
Updates the experimental command to reference the addition of flyPadOS3.
Change the layout so it looks more organized.
=> refactor: experimental command info + copy layout

src/commands/funnies/shomas.ts, src/commands/index.ts
=> feat: add .shomas

src/commands/a32nx/beginner-guide.ts
As discussed on Discord this PR updates the command to provide direct links to specific chapters as a convenience. Adds a little bit more information about the guide in general as well.
Valastiri#8902
=> feat: more detailed beginner guide command

LICENSE, package.json
This PR adds the AGPLv4 License to this repo and updates package.json accordingly.
All contributors have been contacted and have agreed to the change.
N/A
BenW#8484
=> chore: Adds the AGPLv3 License

src/commands/funnies/pw.ts, src/commands/index.ts
requested by boris; .pw command meme
=> feat: .pw command

README.md
Updated logo location on README file.
N/A
=> docs(README): update logo location

src/commands/funnies/p3d.ts
Replaces the .P3D meme gif. Discussed in team channels. 
=> refactor: replace p3d meme

package-lock.json, src/commands/support/calibrate.ts
fixes the url for the calibrate command - as requested by #188 
owen_ #4883
=> refactor: calibrate command url

package-lock.json, src/commands/index.ts, src/commands/support/abbreviations.ts
Serves link to terms and abbreviations docs page
https://docs.flybywiresim.com/pilots-corner/abbreviations/#abbreviations
pererry#8489
=> feat: add .abbreviations command

src/commands/funnies/mico.ts, src/commands/index.ts
Added .mico command for some fun 
zx#0671
=> feat: add .mico command

src/commands/utils/metar.ts
- 'Flight Rules' field has now been added
- CAVOK etc. no longer displays a unit
- Adds degree (°) symbol to wind in METAR breakdown
BenW#8484
=> fix: various .metar improvements

src/commands/support/abbreviations.ts
adds the abb and abrv aliases to the abbreviation command 
owen_ #4883
=> feat: abb and abrv aliases to abbreviation command 

src/commands/index.ts, src/commands/support/airac.ts
Explains the limitation of free SimBrief accounts to AIRAC 2003 and potential issues it can cause.
(updated)
pererry#8489
=> feat: add AIRAC command

README.md
Adds light theme option for the README logo.
=> fix(README): add light theme option

package-lock.json, package.json, src/commands/utils/ping.ts
The ```.ping``` command now has a bad word filter that checks for profane use of language to prevent abuse. Same command but just with a filter.
=> feat(ping): add bad word filter

src/commands/general/translate.ts, src/commands/index.ts
Provides information about various translation efforts with FBW projects. Relatively future proof and additional expansion for more links at the bottom if we decide to translate other aspects using localazy.
Req by Mav, current iteration approved by him as well.
Valastiri#8902
=> feat: translate command

src/commands/a32nx/experimental.ts
To facilitate reporting a new thread was created on Discord: `General Experimental Issue Reports`. 
This PR simply adds the thread to the available appropriate threads list.
Valastiri#8902
=> refactor: add new reporting thread to command

src/commands/index.ts, src/commands/support/github.ts
Adds a command which has a link to the a32nx github page
owen_ #4883
=> feat: a32nx github link command

src/commands/index.ts, src/commands/utils/zulu.ts
adds command .zulu to show the current time in a given UTC-offset timezone. this can be useful given the fact that a majority of active users have their UTC timezone in their nickname (e.g. [Z-4], [Z+11])
=> feat: .zulu command

src/commands/general/msfsdiscord.ts, src/commands/index.ts
Sends a link to the msfs discord server. Requested by nuts. 
oim#0001
=> feat: add .msfsdisc

src/commands/general/latlongfix.ts, src/commands/index.ts
feat: Lat/Long fix conversion chart 
.latlongfix or .llfix
HowNowBrownCrow#2591
=> feat:  Lat/Long fixes cheatsheet

.eslintrc.json, src/commands/a32nx/ctrlE.ts, src/commands/index.ts, src/handlers/ban.ts, src/handlers/messagedelete.ts, src/handlers/messageupdate.ts, src/handlers/scamlog.ts
Fixed all existing linting issues. 
- Renamed ctrl_e to cammelcase ctrlE
- Fixed sparse-array issue
- Adjusted weird string concatination in scamlogs.
=> lint: fix existing linting issues

.eslintrc.json, .github/workflows/pr.yaml, package.json, src/index.ts
Implement CI check for linting. CC: @Benjozork for the original ci.
=> ci: eslint

src/commands/a32nx/simbriefimport.ts
Changes the link used in `.import`
N/A
BenW#8484
=> refactor: simbrief import link

.github/CHANGELOG.md
Synaptic invite was merged without updating changelog. This rectifies this
N/A
BenW#8484
=> docs: update changelog for synaptic

.github/CHANGELOG.md, .github/dependabot.yml
Adds dependabot config to repo to check for package version updates.
- Monthly check
- Ignores minor versions
- Limit of 10 pull requests at a time
=> chore: add dependabot config

.github/CHANGELOG.md, .github/dependabot.yml
Add patch version to ignore list
=> fix(dependabot): ignore patch versions

.github/CHANGELOG.md, src/commands/a32nx/weightBalance.ts
Version indentifier in copy removed. *Future proofs copy for any changes*. User can see docs if we do make changes between versions.
Valasitiri#8902
=> refactor: weight and balance command

.github/CHANGELOG.md, src/commands/a32nx/cfms.ts
Updates wording in `.cfms` as it is also available in stable
BenW#8484
=> refactor: update wording in cfms

src/commands/utils/birthday.ts
Fix birthday ordering by month **and** day, additional optimizations for speed
pererry#8489
=> fix: birthday list ordering

.github/CHANGELOG.md, src/commands/utils/birthday.ts
Switches the birthday permission order so it checks for role before channel
N/A
BenW#8484
=> refactor: switch birthdays permission order

.github/CHANGELOG.md, .github/command-docs.md, src/commands/support/screenshot.ts
Adds `.ss` as an alias to the screenshot command
N/A
BenW#8484
=> refactor: add ss alias in screenshot

package-lock.json, package.json
Updates discord.js from v13.5.1 to v13.8.0 to allow the bot to access voice channel text channels. 
oim#0001
=> chore: update api so bot can access vc text channels

.github/CHANGELOG.md
Adds missing changelog entries from previous 3 PR's
(This PR does not need a changelog entry)
N/A
BenW#8484
=> fix: add missing changelog entries

.github/CHANGELOG.md, .github/CONTRIBUTING.md, .gitignore, docker-compose.yml
This PR adds the docker-compose file to create a local instance of MongoDB and mongo-expressu using Docker.
Read the CONTRIBUTING.md included in this PR test it.
NathanI#8668
=> feat: add docker-compose

.github/CHANGELOG.md, src/commands/utils/birthday.ts, src/handlers/birthdays.ts, src/lib/db.ts, src/lib/schemas/birthdaySchema.ts
Change how the database handling works for the birthday command.
=> refactor: birthday command

.github/CHANGELOG.md, src/commands/a32nx/weather.ts
As recommended by holland: update and amend the copy to be more accurate.
Valastiri#8902
=> refactor: weather.ts embed title and copy

.github/CHANGELOG.md, src/commands/a32nx/beginner-guide.ts
Fixes the changed abbreviations docs link for the beginner's guide command. 
Imenes#0320
=> fix: fixed .bg abbreviations hyperlink

.github/CHANGELOG.md, src/commands/utils/wolframalpha.ts
Fixes the reply embed for no result found
=> fix(wa): missing error embed for no result

.github/CHANGELOG.md, src/commands/general/synaptic.ts
Use a non-vanity Synaptic Discord link as we gain and lose level 3 Boost all the time making the vanity one unreliable. 
Too lazy to run it locally, sorry 😘
nufflee#2003
=> fix: use non-vanity Synaptic Discord link

.github/CHANGELOG.md, src/commands/funnies/cowsay.ts
- Add bad-word filter.
- Add sanitisation for escaping input
- Only allow in bot-commands channel
=> feat: cowsay sanitization

.github/CHANGELOG.md, .github/command-docs.md, src/commands/support/deadzones.ts
Adds .deadzones alias to match docs, adds .deadzone to the github command list as that was missing.
=> refactor: add .deadzones alias to deadzone command

package-lock.json, package.json, src/index.ts
Fixes deployment issues with previous PR
`npm update` used to update packages to compatible versions (solves node_modules errors)
Small update in `index.ts`
Changelog entry not required
N/A
BenW#8484
=> fix: deployment fix for discord.js v14 update

.github/CHANGELOG.md, docker-compose.yml
Adds the bot to the docker-compose
=> chore: bot service to docker-compose

.github/CHANGELOG.md, src/commands/utils/count.ts
Fixes the ping in `.count`
BenW#8484
=> fix: ping in .count

.github/CHANGELOG.md, .github/workflows/pr.yaml
Build and lint helm step for PR.
See checks tab
=> ci: build and lint helm for pr

.github/CHANGELOG.md, src/commands/a32nx/weather.ts
Fixes double space issue for wx command
Also fixes small changelog error
Did this on web at work, can someone else test?
BenW#8484
=> fix: grammar for weather command

.github/CHANGELOG.md, .github/command-docs.md
Moves command categories into 'order of importance'
N/A
BenW#8484
=> refactor: re-ordering of command-docs

.github/CHANGELOG.md, .github/command-docs.md, src/commands/index.ts, src/commands/memes/noHello.ts
Adds the noHello command. Points to `https://nohello.net/en/` as meme
Command message is deleted after use
Requested by Tarek
BenW#8484
=> feat: adds noHello

.github/CHANGELOG.md, src/handlers/scamlog.ts
Fixes a crash in scamlogs caused by non-existent roles.
Fixes a mention missed by previous PR
N/A
BenW#8484
=> fix: crash in scamlogs

.github/CHANGELOG.md
As part of tests in #320, fixed the changelog entry to be correct. 
(Merge performed to check blocking).
Valastiri#8902
=> fix: changelog from testing

.github/CHANGELOG.md, .github/command-docs.md, src/commands/a32nx/airframe.ts, src/commands/a32nx/simbriefimport.ts
Makes .simbrief an alias of the import guide rather than the airframe, as it is almost constantly confused
pererry#8489
=> refactor: simrbief import alias

.github/CHANGELOG.md, .github/command-docs.md
Minor doc update to make the use of `<br>` uniform.
N/A
straks#7240
=> docs: <br> vs <br/> cleanup

.editorconfig, .github/CHANGELOG.md
Creates a standard between most code editors for project settings.
=> chore: add editorconfig

.github/CHANGELOG.md, src/commands/memes/addon.ts, src/commands/memes/boratorium.ts, src/commands/memes/boris.ts, src/commands/memes/bruheg.ts, src/commands/memes/coffee.ts, src/commands/memes/crak.ts, src/commands/memes/default.ts, src/commands/memes/fms.ts, src/commands/memes/fridge.ts, src/commands/memes/guard.ts, src/commands/memes/juan.ts, src/commands/memes/merge.ts, src/commands/memes/mico.ts, src/commands/memes/noHello.ts, src/commands/memes/nut.ts, src/commands/memes/p3d.ts, src/commands/memes/poggers.ts, src/commands/memes/pov.ts, src/commands/memes/ptu.ts, src/commands/memes/pw.ts, src/commands/memes/shame.ts, src/commands/memes/shomas.ts, src/commands/memes/xp.ts
Was suggested/requested by @NathanInnes, so here we go.
Removes unnecessary async/await from memes.
N/A
straks#7240
=> refactor: Removing async/await from memes

.github/CHANGELOG.md, .github/command-docs.md, src/commands/general/notams.ts, src/commands/index.ts
Links to the NOTAMS page of the [website](https://flybywiresim/notams)
=> feat: notams command

.github/CHANGELOG.md, README.md
Improve the readme by removing the A32NX stats and the line about contacting three people.
N/A
Awemeter#3110
=> docs: Improve readme

.github/CHANGELOG.md, src/handlers/scamlog.ts
- Adds error handling to muting the user.
- General cleanup of code.
When failing to add user role it throws an error.
=> refactor(scamlog): add error handling and code cleanup

.github/CHANGELOG.md, src/index.ts
Adds error handling for process start.
=> feat: error handling for process start

.github/CHANGELOG.md, src/commands/general/headwind.ts, src/commands/general/salty.ts, src/commands/general/synaptic.ts
If I have missed any invites lmk.
- Removes unnecessary async/await from invites. 
N/A
=> refactor: remove async/await from invites

.github/CHANGELOG.md, .github/command-docs.md, src/commands/general/msfsdiscord.ts, src/commands/memes/shame.ts, src/commands/memes/xp.ts
- Removes async functions as unnecessary.
- Removes msg delete.
=> refactor(msfs/memes): remove async/delete msg 

.github/CHANGELOG.md, .github/command-docs.md, src/commands/general/website.ts, src/commands/index.ts
Provides a link to the main [website](https://flybywiresim.com/)
=> feat: website command

.github/CHANGELOG.md, .github/command-docs.md, src/commands/index.ts, src/commands/support/simulationRate.ts
Introduces a Simulation Rate support command to explain the behavior of
the Simulation Rate limiter in place.
straks#7240
=> feat: simrate command

.github/CHANGELOG.md, src/commands/support/ctd.ts, src/commands/support/tug.ts, src/commands/support/utf-8.ts
Change 3 links to match changes in https://github.com/flybywiresim/docs/pull/631
Needs to be merged after the docs PR is merged. 
N/A
Cdr_Maverick#6475
=> refactor: corrected links for update to reported issues page on docs

.github/CHANGELOG.md, .github/command-docs.md, src/commands/general/dfd.ts, src/commands/index.ts
Adds a `.dfd` command which provides a link to the Digital Flight Dynamics Discord server.
trust me bro
nufflee#2003
=> feat: add dfd command

.github/CHANGELOG.md, src/commands/support/dlss.ts
Updating the command to highlight the blurry displays first and explain it is an MSFS issue. 
straks#7240
=> refactor: Improve DLSS data to highlight blurry displays

.github/CHANGELOG.md, src/commands/moderation/ban.ts, src/commands/moderation/unban.ts, src/handlers/ban.ts
When a mod manual bans a user (not using the banCommand), the banHandler gets executed. This will trigger a modLog message indicating this has happened. This modLog message includes the moderator executing the ban and an embed with the details of who is banned, by whom and why.
The next ban using the banCommand, the bot will execute the banCommand through the createMessageHandler.
When the ban happens through the banCommand, the banHandler is still executed because it is still a ban on the server. And while it should not post anything because it should recognize that the command was executed by the bot, it posts a modLog message as if it is a manual ban by the same moderator of the previous manual ban. However, this modLog message embed does not contain the reason, or the moderator …
=> refactor: ban and unban commands stability improvements and ban handler fixes for manual bans

.github/CHANGELOG.md, src/handlers/scamlog.ts
Scam protection has now been changed to use the timeout feature instead of a 'muted' role. 
The order or execution has also been changed so that the DM is sent after the timeout is successful. If the timeout is unsuccessful, it will notify moderators and not send a DM to the user.
The user will be timed out for a week while appropriate action is determined by moderators. 
Timeout Error:
Successful Timeout (Lets party!):
DM:
BenW#8484
=> feat: scam protection to use timeout

.github/CHANGELOG.md, src/commands/a32nx/atc.ts
=> fix: language on ATC command 

.github/CHANGELOG.md, src/commands/moderation/welcome.ts
Youtube is changing the way to reach accounts/channels. This means the URL for the Youtube account has changed to: https://www.youtube.com/@FlyByWireSimulations (the old one still works as well). 
There's only one place in the bot this URL is mentioned, in the welcome message, so updating it there. 
straks#7240
=> refactor: update youtube account information

.github/CHANGELOG.md, src/commands/moderation/ban.ts
Ban command can now purge messages. It requires an extra argument between and including 0 - 7.
This number indicates the number of days of messages to purge. If the <reason> arg begins with a number, this will be treated as the <days> arg. This would be an edge case as reason never usually begins with a number. However, this can be looked at and refactored if needed.
BenW#8484
=> feat: purge messages on ban

.github/CHANGELOG.md, src/commands/support/wasm.ts
As requested, did change it to 15 minutes as we've seen reports of that.
straks#7240
=> refactor: update wasm command with extra details

.github/CHANGELOG.md, .github/command-docs.md, src/commands/index.ts, src/commands/support/simbridgeLog.ts
Information on how to locate and send SimBridge log for support.
BenW#8484
=> feat: SimBridge log command

.github/CHANGELOG.md, src/commands/moderation/timeout.ts
When timing out, it now automatically warns the user, using the timeout reason for the warn reason. This is useful for automatic long term logging of why someone has been timed out.
Mod Log:
DM:
Warn Logged:
BenW#8484
=> feat: warns a user when timed out

.github/CHANGELOG.md, src/commands/aircraft/weightBalance.ts
Stable now has the W&B in EFB as well. Used the opportunity to move it to a simple MessageCommand as well.
straks#7240
=> refactor: update wb command for change in Stable

.github/CHANGELOG.md, src/commands/aircraft/remoteMcdu.ts, src/commands/aircraft/weather.ts
As discussed with Oim fixes a couple of outdated links and information in a couple of commands:
- wx
- remotemcdu
If there are more that may need changes can include them with this PR.
Valastiri#8902
=> refactor: outdated information + links in commands

.github/CHANGELOG.md, src/commands/aircraft/atc.ts
Refactors in line with flybywiresim/docs#691
straks#7240
=> refactor: update atc command with new link and information

.github/CHANGELOG.md, src/commands/index.ts, src/commands/support/simbridgeLog.ts
=> fix: code typo on simbridgeLog command

src/commands/support/botIssue.ts
=> fix: botIssue.ts spelling

.github/CHANGELOG.md, src/commands/memes/addon.ts
updated the .addon meme link to the new one 
https://cdn.discordapp.com/attachments/740722295009706034/1072687692573315204/addon.png
LunakisLeaks#7744
=> fix: .addon command

.github/CHANGELOG.md, .github/command-docs.md, src/commands/aircraft/gsxIntegration.ts, src/commands/index.ts
=> feat: Add GSX Integration command

.github/CHANGELOG.md, .github/command-docs.md, src/commands/aircraft/weather.ts
The first paragraph was inaccurate and the short commands were not great (e.g. wxr is much more likely to come to mind than wx).
The reasons we cannot implement even the weather map on the ND are actually, roughly in order of importance:
- the map projection used by the MSFS weather map is different to the ND,
- the image rendering/style cannot be sufficiently customised to match any of the A320 WxR LRUs,
- there is no way to access hazard data for the icons shown by the RDR4000,
- we did have some perf issues in the past but it's unclear whether this would be the case for a new implementation,
An actual weather radar (aside from the ND map) requires even more from the sim.
=> fix: Improve wxr and terr command

.github/CHANGELOG.md, src/commands/aircraft/efb.ts, src/commands/memes/pov.ts
Uses downscaled gifs for EFB and POV
BenW#8484
=> refactor: downscaled gifs

.github/CHANGELOG.md, src/commands/support/supportGuide.ts
Add a link to the support channel to the support Guide command.
Slein#8982
=> fix: add link for support channel to sg

.github/CHANGELOG.md, src/commands/moderation/rules.ts
Updating rules to clarify purpose of the community and what is tolerated.
straks#7240
=> fix: updating rules

.github/CHANGELOG.md, src/commands/memes/noHello.ts
Don't delete nohello message if there is more content added.
Slein#8982
=> feat: don't delete nohello with custom content

.github/CHANGELOG.md, src/commands/utils/simbriefdata.ts
adds information about the airac cycle to the simbriefdata command
Slein#8982
=> feat: add airac cycle to simbriefdata

.github/CHANGELOG.md, src/commands/aircraft/versions.ts
Updates the links in the `.versions` command.
Fixes #452 
BenW#8484
=> refactor: update versions links

.github/CHANGELOG.md, src/commands/aircraft/holds.ts
Fixed a word from plural to singular form
one letter change, didn't test
Lauvan#3330
=> fix: typo in holds

.github/CHANGELOG.md
=> fix: changelog merge error

.github/CHANGELOG.md, src/commands/aircraft/versions.ts
Fix a small typo in .versions command
=> fix: typo in versions.ts

src/commands/general/spad.ts
Fixing URL based on website
straks
=> fix: Fix URL based on Spad.neXt website

.github/CHANGELOG.md, src/commands/support/simbridgeDebug.ts
Fixing the string that has to be put into cmd, as it's currently wrong (https://discord.com/channels/738864299392630914/897491699167793182/1167871264652800030)
N/A
Lauvaan
=> fix: typo in .simbridgedebug command

.github/CHANGELOG.md, .github/workflow_scripts/cf-cdn.sh
In preparation for the new bot, this PR changes the CDN upload URL  to organise the R2 bucket introducing a folder for the old bot (this), new bot (utils) and sticky bot (sticky).
Once this PR is merged, the IMAGE_BASE_URL secrets on this repo must be changed to reflect.
N/A
benw8484
=> refactor: change cdn url

.github/CHANGELOG.md, src/commands/support/econnreset.ts
Fixes #523
This PR change `.econreset` | `.econnreset` description:
From: `To verify that this issue is not caused by your Internet Service Provider, please use a VPN service with the connection location set to the US and try again.`
To: `To verify that this issue is not caused by your Internet Service Provider, please use a VPN service and try again.`
`LunakisLeaks`
=> fix: update econnreset description

.github/CHANGELOG.md, src/commands/index.ts
Disable all commands that will be migrated to the new bot in discord-bot-utils#85
straks
=> Feat: Disable prefix commands for migration
